trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Cambia si tu agente tiene otro nombre

variables:
  buildConfiguration: 'Release'
  versionFilePath: 'Common/version'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: Bash@3
  displayName: 'Leer versión desde archivo'
  inputs:
    targetType: 'inline'
    script: |
      version=$(cat $(versionFilePath))
      echo "##vso[task.setvariable variable=PACKAGE_VERSION]$version"
      echo "Versión leída: $version"

- script: |
    dotnet restore GTM.Common.sln
  displayName: 'Restaurar dependencias'

- script: |
    dotnet build GTM.Common.sln --configuration $(buildConfiguration)
  displayName: 'Compilar solución'

- script: |
    dotnet pack Common/Common.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:PackageVersion=$(PACKAGE_VERSION)
  displayName: 'Empaquetar NuGet con versión $(PACKAGE_VERSION)'

- task: NuGetAuthenticate@1
  displayName: 'Autenticar con Azure Artifacts'

- task: NuGetCommand@2
  displayName: 'Subir paquete al feed privado'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'gtm.common.package'
